In [17]:
import importlib
import sys
from urllib.request import urlretrieve

# Install drake (and underactuated).
if 'google.colab' in sys.modules and importlib.util.find_spec('underactuated') is None:
    urlretrieve(f"http://underactuated.csail.mit.edu/scripts/setup/setup_underactuated_colab.py",
                "setup_underactuated_colab.py")
    from setup_underactuated_colab import setup_underactuated
    setup_underactuated(underactuated_sha='15cfd96b0bdfd1b0c67597c24f91907776c02a6d', drake_version='0.27.0', drake_build='release')

server_args = []
if 'google.colab' in sys.modules:
  server_args = ['--ngrok_http_tunnel']
# Start a single meshcat server instance to use for the remainder of this notebook.
from meshcat.servers.zmqserver import start_zmq_server_as_subprocess
proc_planar, zmq_url_planar, web_url_planar = start_zmq_server_as_subprocess(server_args=server_args)
proc, zmq_url, web_url = start_zmq_server_as_subprocess(server_args=server_args)

import numpy as np
from ipywidgets import FloatSlider, ToggleButton
from IPython.display import display, SVG, HTML
import pydot

import pydrake.all
from pydrake.all import (
    MultibodyPlant, DiagramBuilder, LinearQuadraticRegulator, Saturation, SceneGraph, Simulator, 
    WrapToSystem, AddMultibodyPlantSceneGraph, Parser, MathematicalProgram, eq, PiecewisePolynomial,
    SnoptSolver, TrajectorySource, MultibodyPositionToGeometryPose, PlanarSceneGraphVisualizer
)
from pydrake.examples.acrobot import AcrobotPlant, AcrobotGeometry
from pydrake.systems.jupyter_widgets import WidgetSystem
from pydrake.common.containers import namedview
from underactuated import FindResource, ManipulatorDynamics
from underactuated.jupyter import running_as_notebook


## Problem Description

We want to write a nonlinear optimization for the ball balancing bot. In order to complete our trajectory optimization, we will use `MathematicalProgram`.

**maybe write more later if we submit the notebook

## Parse the `urdf` and Get the `MultibodyPlant`

We start by defining a couple of physical parameters that we will need below.

In [18]:
ballbot_urdf = """
<?xml version="1.0"?>

<robot xmlns="http://drake.mit.edu"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 name="BallBot">

  <link name="ground">
    <visual>
      <origin xyz="0 0 -5" rpy="0 0 0" />
      <geometry>
        <box size="1000 1000 10" />
      </geometry>
      <material>
        <color rgba="0.93 .74 .4 1" />
      </material>
    </visual>
  </link>

  <joint name="ground_weld" type="fixed">
    <parent link="world" />
    <child link="ground" />
  </joint>

  <link name="ball">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <inertia ixx=".002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius=".1" />
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material>
        <color rgba="0.25 0.52 0.96 1" />
      </material>
    </visual>
  </link>

  <link name="bot">
    <inertial>
      <origin xyz="0 0 .05" rpy="0 0 0" />
      <mass value="4" />
      <inertia ixx="0.018" ixy="0" ixz="0" iyy="0.018" iyz="0" izz="0.0288" />
    </inertial>
    <visual>
      <origin xyz="0 0 .05" rpy="0 0 0" />
      <geometry>
         <cylinder length=".1" radius=".12" />
      </geometry>
      <material>
        <color rgba=".61 .63 .67 1" />
      </material>
    </visual>
  </link>
  
  <joint name="x" type="prismatic">
    <parent link="world" />
    <child link="ball" />
    <origin xyz="0 0 .1" />
    <axis xyz="1 0 0" />
    <dynamics damping="0.1" />
  </joint>

  <joint name="theta" type="continuous">
    <parent link="ball" />
    <child link="bot" />
    <origin xyz="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics damping="0.1" />
  </joint>

  <transmission type="SimpleTransmission" name="ball_torque">
    <actuator name="torque" />
    <joint name="theta" />
    <mechanicalReduction>1</mechanicalReduction>
  </transmission>

  <transmission type="SimpleTransmission" name="ball_force">
    <actuator name="force" />
    <joint name="x" />
    <mechanicalReduction>.1</mechanicalReduction>
  </transmission>
</robot>
"""

## The Trajectory Optimization Problem

We start by setting some parameters of our optimization problem.

Here are part of the constraints of the optimization problem:


1.   Time steps need to be bounded between h_min and h_max
2.   Map configurations, velocities, accelerations to each other using the Euler method
3.   Something about dynamics
4.   Want the thing on top to be horizonal at the end (theta1 = 0, theta2 = 0)
5.   Can add an angle bound (like it can't be more than 15 deg away from horizontal)



Here we set the initial guess for our optimization problem.

For the time steps `h` we just initialize them to their maximal value `h_max` (somewhat an arbitrary decision, but it works).

For the robot configuration `q`, we interpolate between the initial value `q0_guess` and the final value `- q0_guess`.
In our implementation, the value given below for `q0_guess` made the optimization converge.
But, if you find the need, feel free to tweak this parameter.
The initial guess for the velocity and the acceleration is obtained by differentiating the one for the position.

The normal force `f` at the stance foot is equal to the total `weight` of the robot.

All the other optimization variables are initialized at zero.
(Note that, if the initial guess for a variable is not specified, the default value is zero.)

We can finally solve the problem! Be sure that the solver actually converged: you can check this by looking at the variable result.is_success() (printed below).

In the following cell we retrieve the optimal value of the decision variables.

## Animate the Result

Here we quickly build a Drake diagram to animate the result we got from trajectory optimization: useful for debugging your code and to be sure that everything looks good.

In [48]:
class optimization_step:
  def __init__(self, start, goal, T, actuation_lim, h_min = 0.005, 
               h_max = 0.05):
    self.start = start
    self.goal = goal
    self.T = T
    self.actuation_lim = actuation_lim
    self.h_min = h_min
    self.h_max = h_max
  #  self.max_control = max_control
  #  self.min_control = min_control

  def create_plant(self, ballbot_urdf):
    self.ballbot_2D = MultibodyPlant(time_step=0)
    Parser(self.ballbot_2D).AddModelFromString(ballbot_urdf, "urdf")
    self.ballbot_2D.Finalize()

    # overwrite MultibodyPlant with its autodiff copy
    self.ballbot_2D = self.ballbot_2D.ToAutoDiffXd() 

    # number of configuration variables
    self.nq = self.ballbot_2D.num_positions()  # Returns the size of the multibody system state vector x = [q v]. This will be num_positions() plus num_velocities()

  def ballbot2D_dynamics(self, vars):
    split_at = [self.nq, 2 * self.nq, 3 * self.nq]
    q, qd, qdd, u = np.split(vars, split_at)
    
    # set compass gait state
    context = self.ballbot_2D.CreateDefaultContext()
    self.ballbot_2D.SetPositions(context, q)
    self.ballbot_2D.SetVelocities(context, qd)
    self.ballbot_2D.get_actuation_input_port().FixValue(context, u)
    
    # matrices for the manipulator equations
    M, Cv, tauG, B, tauExt = ManipulatorDynamics(self.ballbot_2D,q,qd)
    theta = q[1]

    # return violation of the manipulator equations
    return M.dot(qdd) + Cv - tauG -B@u - tauExt

  def generate_cont_vars(self, prog):

    """ Returns h, q, qd, qdd, u """
    # vector of the time intervals
    # (distances between the T + 1 break points)
    T = self.T
    nq = self.nq
    h = prog.NewContinuousVariables(T, name='h')

    # system configuration, generalized velocities, and accelerations
    q = prog.NewContinuousVariables(rows=T+1, cols=nq, name='q')
    qd = prog.NewContinuousVariables(rows=T+1, cols=nq, name='qd')
    qdd = prog.NewContinuousVariables(rows=T, cols=nq, name='qdd')

    # actuation
    u = prog.NewContinuousVariables(rows=T, cols=nq, name='u')

    return h, q, qd, qdd, u

  def set_initial_guess(self, prog, h_max, T, h, q, qd, qdd):
    # vector of the initial guess
    initial_guess = np.empty(prog.num_vars())

    # initial guess for the time step
    h_guess = h_max
    prog.SetDecisionVariableValueInVector(h, [h_guess] * T, initial_guess)

    # linear interpolation of the configuration
    q0_guess = np.array([0, .15])
    q_guess_poly = PiecewisePolynomial.FirstOrderHold(
        [0, T * h_guess],
        np.column_stack((q0_guess, - q0_guess))
    )
    qd_guess_poly = q_guess_poly.derivative()
    qdd_guess_poly = q_guess_poly.derivative()

    # set initial guess for configuration, velocity, and acceleration
    q_guess = np.hstack([q_guess_poly.value(t * h_guess) for t in range(T + 1)]).T
    qd_guess = np.hstack([qd_guess_poly.value(t * h_guess) for t in range(T + 1)]).T
    qdd_guess = np.hstack([qdd_guess_poly.value(t * h_guess) for t in range(T)]).T
    prog.SetDecisionVariableValueInVector(q, q_guess, initial_guess)
    prog.SetDecisionVariableValueInVector(qd, qd_guess, initial_guess)
    prog.SetDecisionVariableValueInVector(qdd, qdd_guess, initial_guess)

    return initial_guess

  def simulate(self, result, h, q, qd, qdd):
    T = self.T
    # get optimal solution
    h_opt = result.GetSolution(h)
    q_opt = result.GetSolution(q)
    qd_opt = result.GetSolution(qd)
    qdd_opt = result.GetSolution(qdd)

    # stack states
    x_opt = np.hstack((q_opt, qd_opt))

    # interpolate state values for animation
    time_breaks_opt = np.array([sum(h_opt[:t]) for t in range(T+1)])
    x_opt_poly = PiecewisePolynomial.FirstOrderHold(time_breaks_opt, x_opt.T)

    # parse urdf with scene graph
    ballbot = MultibodyPlant(time_step=0)
    scene_graph = SceneGraph()
    ballbot.RegisterAsSourceForSceneGraph(scene_graph)
    Parser(ballbot).AddModelFromString(ballbot_urdf, "urdf")
    ballbot.Finalize()

    # build block diagram and drive system state with
    # the trajectory from the optimization problem
    builder = DiagramBuilder()
    source = builder.AddSystem(TrajectorySource(x_opt_poly))
    builder.AddSystem(scene_graph)
    pos_to_pose = builder.AddSystem(MultibodyPositionToGeometryPose(ballbot, input_multibody_state=True))
    builder.Connect(source.get_output_port(0), pos_to_pose.get_input_port())
    builder.Connect(pos_to_pose.get_output_port(), scene_graph.get_source_pose_port(ballbot.get_source_id()))

    # add visualizer
    xlim = [-.75, .75]
    ylim = [-.2, 1.5]
    visualizer = builder.AddSystem(PlanarSceneGraphVisualizer(scene_graph, xlim=xlim, ylim=ylim, show=False))
    builder.Connect(scene_graph.get_pose_bundle_output_port(), visualizer.get_input_port(0))
    simulator = Simulator(builder.Build())

    # generate and display animation
    visualizer.start_recording()
    simulator.AdvanceTo(x_opt_poly.end_time())
    ani = visualizer.get_recording_as_animation()
    return ani
  

    # --------------- Various Optimization Setups -----------

  def no_cost(self):
    T = self.T
    h_min = self.h_min
    h_max = self.h_max
    goal = self.goal
    start = self.start
    actuation_lim = self.actuation_lim
    nq = self.nq
    # initialize program
    prog = MathematicalProgram()
    h, q, qd, qdd, u = self.generate_cont_vars(prog)

    # 1. lower and upper bound on the time steps for all t
    prog.AddBoundingBoxConstraint([h_min] * T, [h_max] * T, h)

    # 2. link the configurations, velocities, and accelerations
    # uses implicit Euler method, https://en.wikipedia.org/wiki/Backward_Euler_method
    for t in range(T):
        prog.AddConstraint(eq(q[t+1], q[t] + h[t] * qd[t+1]))
        prog.AddConstraint(eq(qd[t+1], qd[t] + h[t] * qdd[t]))

    # 3. drake dynamics
    for t in range(T):
      vars = np.concatenate((q[t], qd[t], qdd[t], u[t]))
      prog.AddConstraint(self.ballbot2D_dynamics, lb=[0]*nq, ub=[0]*nq, vars=vars)
      prog.AddLinearConstraint(u[t][0] == u[t][1])  

    # 4. horizontal at end
    # q = [x, theta1]
    prog.AddLinearConstraint(q[-1][1] == goal[1])

    # at the origin at the end
    prog.AddLinearConstraint(q[-1][0] == goal[0])

    # give start position
    prog.AddLinearConstraint(q[0][0] == start[0])
    prog.AddLinearConstraint(q[0][1] == start[1])

    initial_guess = self.set_initial_guess(prog, h_max, T, h, q, qd, qdd)

    # solve mathematical program with initial guess
    solver = SnoptSolver()
    result = solver.Solve(prog, initial_guess)
    print(f'Solution found? {result.is_success()}.')

    return result, h, q, qd, qdd

  
  def distance_cost(self):
    T = self.T
    h_min = self.h_min
    h_max = self.h_max
    goal = self.goal
    start = self.start
    actuation_lim = self.actuation_lim
    nq = self.nq
    # initialize program
    prog = MathematicalProgram()
    h, q, qd, qdd, u = self.generate_cont_vars(prog)

    # 1. lower and upper bound on the time steps for all t
    prog.AddBoundingBoxConstraint([h_min] * T, [h_max] * T, h)

    # 2. link the configurations, velocities, and accelerations
    # uses implicit Euler method, https://en.wikipedia.org/wiki/Backward_Euler_method
    for t in range(T):
        prog.AddConstraint(eq(q[t+1], q[t] + h[t] * qd[t+1]))
        prog.AddConstraint(eq(qd[t+1], qd[t] + h[t] * qdd[t]))

    # 3. drake dynamics
    for t in range(T):
      vars = np.concatenate((q[t], qd[t], qdd[t], u[t]))
      prog.AddConstraint(self.ballbot2D_dynamics, lb=[0]*nq, ub=[0]*nq, vars=vars)
      prog.AddLinearConstraint(u[t][0] == u[t][1])

    # 4. Penalize time away from goal
    total = 0
    for t in range(T):
      total += (q[t][1]**2)**0.5
      total += (q[t][0]**2)**0.5
    prog.AddCost(total)  

    # 5. goal at end
    prog.AddLinearConstraint(q[-1][1] == goal[1])
    prog.AddLinearConstraint(q[-1][0] == goal[0])

    # give start position
    prog.AddLinearConstraint(q[0][0] == start[0])
    prog.AddLinearConstraint(q[0][1] == start[1])

    initial_guess = self.set_initial_guess(prog, h_max, T, h, q, qd, qdd)

    # solve mathematical program with initial guess
    solver = SnoptSolver()
    result = solver.Solve(prog, initial_guess)
    print(f'Solution found? {result.is_success()}.')

    return result, h, q, qd, qdd

  def quadratic_distance_cost(self):
    T = self.T
    h_min = self.h_min
    h_max = self.h_max
    goal = self.goal
    start = self.start
    actuation_lim = self.actuation_lim
    nq = self.nq

    # initialize program
    prog = MathematicalProgram()
    h, q, qd, qdd, u = self.generate_cont_vars(prog)

    # 1. lower and upper bound on the time steps for all t
    prog.AddBoundingBoxConstraint([h_min] * T, [h_max] * T, h)

    # 2. link the configurations, velocities, and accelerations
    # uses implicit Euler method, https://en.wikipedia.org/wiki/Backward_Euler_method
    for t in range(T):
        prog.AddConstraint(eq(q[t+1], q[t] + h[t] * qd[t+1]))
        prog.AddConstraint(eq(qd[t+1], qd[t] + h[t] * qdd[t]))

    # 3. drake dynamics
    for t in range(T):
      vars = np.concatenate((q[t], qd[t], qdd[t], u[t]))
      prog.AddConstraint(self.ballbot2D_dynamics, lb=[0]*nq, ub=[0]*nq, vars=vars)
      prog.AddLinearConstraint(u[t][0] == u[t][1])

    # 4. Penalize time away from goal
    total = 0
    for t in range(T):
      total += q[t][1]**2
      total += q[t][0]**2
    prog.AddCost(total)  

    # 5. goal at end
    prog.AddLinearConstraint(q[-1][1] == goal[1])
    prog.AddLinearConstraint(q[-1][0] == goal[0])

    # give start position
    prog.AddLinearConstraint(q[0][0] == start[0])
    prog.AddLinearConstraint(q[0][1] == start[1])

    # 6. actuation constraint
    if actuation_lim is not None:
      for t in range(T):
        vars = np.concatenate((q[t], qd[t], qdd[t], u[t]))
        prog.AddLinearConstraint(u[t][0] <= actuation_lim)
        prog.AddLinearConstraint(u[t][0] >= -1* actuation_lim)

    initial_guess = self.set_initial_guess(prog, h_max, T, h, q, qd, qdd)

    # solve mathematical program with initial guess
    solver = SnoptSolver()
    result = solver.Solve(prog, initial_guess)
    print(f'Solution found? {result.is_success()}.')

    return result, h, q, qd, qdd

In [41]:
start = [-.2, 0.7]
goal = [0, 0]
T = 50
actuation_lim = None

step = optimization_step(start, goal, T, actuation_lim)
step.create_plant(ballbot_urdf)
HTML(step.simulate(*step.no_cost()).to_jshtml())

Solution found? True.


In [51]:
start = [-.2, 0.7]
goal = [0, 0]
T = 50
actuation_lim = None

step = optimization_step(start, goal, T, actuation_lim)
step.create_plant(ballbot_urdf)
HTML(step.simulate(*step.quadratic_distance_cost()).to_jshtml())

Solution found? True.


In [93]:
def model_predictive_control(start, goal, optimizer, time_steps, horizon, state_noise, actuator_noise, actuation_lim = None):
  # 1. take current state (or initial condition)
  # 2. solve optimization problem
  # 3. take first commanded u from problem
  # 3. add actuator noise
  # 4. execute for a step
  # 5. add state noise
  
  current_state = start
  for i in range(time_steps):
    print(f'Beginning step {i} of {time_steps}...')
    step = optimization_step(current_state, goal, horizon, actuation_lim)
    step.create_plant(ballbot_urdf)
    result, h, q, qd, qdd = optimizer(step)

    # get optimal solution
    h_opt = result.GetSolution(h)
    q_opt = result.GetSolution(q)
    qd_opt = result.GetSolution(qd)
    qdd_opt = result.GetSolution(qdd)

    # stack states
    x_opt = np.hstack((q_opt, qd_opt))

    # interpolate state values for animation
    time_breaks_opt = np.array([sum(h_opt[:t]) for t in range(horizon+1)])
    x_opt_poly = PiecewisePolynomial.FirstOrderHold(time_breaks_opt, x_opt.T)
    next_state = x_opt_poly.value(1) # this is the full state vector, including x_dot and theta_dot
    
    print(f'current state is: \n {current_state}\n')
    print(f'next state is: \n {next_state}\n\n')
    current_state = next_state

In [94]:
start = [-.2, 0.7]
goal = [0, 0]
optimizer = optimization_step.quadratic_distance_cost
time_steps = 50
horizon = 40
state_noise = np.random.rand
actuator_noise = np.random.rand

model_predictive_control(start, goal, optimizer, time_steps, horizon, state_noise, actuator_noise)


Beginning step 0 of 50...
Solution found? True.
current state is: 
 [-0.2, 0.7]

next state is: 
 [[0.        ]
 [0.        ]
 [0.33481014]
 [0.03005211]]


Beginning step 1 of 50...
Solution found? True.
current state is: 
 [[0.        ]
 [0.        ]
 [0.33481014]
 [0.03005211]]

next state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.46380117e-06]]


Beginning step 2 of 50...
Solution found? True.
current state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.46380117e-06]]

next state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.46380117e-06]]


Beginning step 3 of 50...
Solution found? True.
current state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.46380117e-06]]

next state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.46380117e-06]]


Beginning step 4 of 50...
Solution found? True.
current state is: 
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.84842985e-06]
 [ 3.4638011

KeyboardInterrupt: ignored